spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sbook?useSSL=false&serverTimezone=GMT&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yangyihi2001
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  # 配置redis
  redis:
    host: 192.168.0.105 #Redis服务器地址
    password: 410327
    port: 6379 #Redis服务器连接端口
    database: 0   #Redis数据库索引（默认为0）
    timeout: 1800000  #连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 20  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 5  #连接池中的最大空闲连接
        min-idle: 0  #连接池中的最小空闲连接
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)

#配置mybatis
mybatis-plus:
  #启动bean实体类简化写法
  type-aliases-package: com.example.sstest.bean
  mapper-locations: classpath:mapper/*.xml
  #  config-location: classpath:mybatis/mybatis-config.xml
  #注意有了configuration配置，就不能配置config-location了
  configuration: #指定mybatis的全局配置
    # 配置驼峰命名 自动注入
    map-underscore-to-camel-case: true
  global-config:
    banner: false

server:
  port: 8888
